fix contract transfer failed for endorser
xuperchain/xuperchain pull request #1133
Opened 2022-03-01 12:01 UTC by godeamon

修复在背书场景下调用合约时同时转账给合约失败的问题。

2022-03-04 07:38 UTC, chenfengjin requested changes

2022-03-04 07:38 UTC, chenfengjin commented on cmd/client/cmd/comm_trans.go
> +			return nil, fmt.Errorf("Invalid Amount: %s", c.Amount)
通常go 语言的 error 字符串首字母都不需要大写，因为error string 之前会有其他信息
考虑控制台显示的日志

t=2022-03-04T15:06:40+0800 lvl=dbug msg="Invalid Amount:" module=xchain log_id=1646376804_7594503152463715 s_mod=ledger call=ledger.go:815 pid=9246 blkTimer=saveHeader:0.10ms,saveAllTxs:0.12ms,saveToDisk:0.12ms,total:0.35ms

和

t=2022-03-04T15:06:40+0800 lvl=dbug msg="invalid amount:" module=xchain log_id=1646376804_7594503152463715 s_mod=ledger call=ledger.go:815 pid=9246 blkTimer=saveHeader:0.10ms,saveAllTxs:0.12ms,saveToDisk:0.12ms,total:0.35ms

后者会更好一些

2022-03-04 07:38 UTC, chenfengjin commented on cmd/client/cmd/comm_trans.go
> +			fmt.Printf("amount convert to bigint failed")
用通用的日志库来打日志，方便进行过滤，采集等等

2022-03-04 07:38 UTC, chenfengjin commented on cmd/client/cmd/comm_trans.go
> +			fmt.Printf("amount convert to bigint failed")
上层会处理错误信息吗？
如果有的话在出错的时候这里的错误信息会在控制台出现两次

2022-03-04 07:49 UTC, godeamon commented on cmd/client/cmd/comm_trans.go
> +			return nil, fmt.Errorf("Invalid Amount: %s", c.Amount)
cli 里都是这样写的，我就是cp的。。。

2022-03-04 07:49 UTC, godeamon commented on cmd/client/cmd/comm_trans.go
> +			fmt.Printf("amount convert to bigint failed")
这个就是 cli，不用 log 到文件。

2022-03-04 08:00 UTC, wangchao0222 approved these changes

2022-03-07 02:58 UTC, godeamon commented on cmd/client/cmd/comm_trans.go
> +			return nil, fmt.Errorf("Invalid Amount: %s", c.Amount)
已改小写。

2022-03-07 02:58 UTC, godeamon commented on cmd/client/cmd/comm_trans.go
> +			fmt.Printf("amount convert to bigint failed")
已改。

2022-03-07 07:58 UTC, chenfengjin approved these changes

2022-03-07 08:00 UTC, merged